# Generated by Django 4.1 on 2023-06-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cryto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                ("available_exchanges", models.CharField(max_length=100)),
                ("currency_base", models.CharField(max_length=50)),
                ("currency_quote", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Forex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10)),
                ("currency_group", models.CharField(max_length=20)),
                ("currency_base", models.CharField(max_length=30)),
                ("currency_quote", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Stocks",
            fields=[
                (
                    "ticker",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("company_name", models.CharField(max_length=300)),
                ("currency", models.CharField(max_length=5)),
                ("exchange", models.CharField(max_length=10)),
                ("mic_code", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=30)),
                ("security_type", models.CharField(max_length=50)),
                ("sp500", models.BooleanField()),
                ("ftse_100", models.BooleanField()),
                ("nasdaq_100", models.BooleanField()),
            ],
        ),
    ]
