# Generated by Django 4.1 on 2023-06-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Crypto",
            fields=[
                (
                    "symbol",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("available_exchanges", models.CharField(max_length=100)),
                ("currency_base", models.CharField(max_length=50)),
                ("currency_quote", models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(name="Cryto",),
        migrations.RemoveField(model_name="forex", name="id",),
        migrations.AlterField(
            model_name="forex",
            name="symbol",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
