# Generated by Django 4.1 on 2023-06-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_crypto_delete_cryto_remove_forex_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocks",
            name="last_updated",
            field=models.DateField(default="1901-01-01"),
        ),
    ]
