# Generated by Django 4.1 on 2023-07-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_stocks_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocks",
            name="ask",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="askSize",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="averageDailyVolume10Day",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="averageVolume",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="averageVolume10days",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="beta",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="bid",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="bidSize",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="bookValue",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="currentPrice",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="currentRatio",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="dateShortInterest",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="dayHigh",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="dayLow",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="debtToEquity",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="dividendRate",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="dividendYield",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="earningsGrowth",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="earningsQuarterlyGrowth",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="ebitda",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="ebitdaMargins",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="enterpriseToEbitda",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="enterpriseToRevenue",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="enterpriseValue",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="fiftyDayAverage",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="fiftyTwoWeekChange",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="fiftyTwoWeekHigh",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="fiftyTwoWeekLow",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="fiveYearAvgDividendYield",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="floatShares",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="forwardEps",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="forwardPE",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="freeCashflow",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="grossMargins",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="grossProfits",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="heldPercentInsiders",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="heldPercentInstitutions",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="impliedSharesOutstanding",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="lastDividendDate",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="lastDividendValue",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="lastFiscalYearEnd",
            field=models.DateField(default="1901-01-01"),
        ),
        migrations.AddField(
            model_name="stocks",
            name="lastSplitDate",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="lastSplitFactor",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="marketCap",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="mostRecentQuarter",
            field=models.DateField(default="1901-01-01"),
        ),
        migrations.AddField(
            model_name="stocks",
            name="netIncomeToCommon",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="nextFiscalYearEnd",
            field=models.DateField(default="1901-01-01"),
        ),
        migrations.AddField(
            model_name="stocks",
            name="open",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="operatingCashflow",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="operatingMargins",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="payoutRatio",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="pegRatio",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="previousClose",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="priceToBook",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="priceToSalesTrailing12Months",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="profitMargins",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="quickRatio",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="regularMarketDayHigh",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="regularMarketDayLow",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="regularMarketOpen",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="regularMarketPreviousClose",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="regularMarketVolume",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="returnOnAssets",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="returnOnEquity",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="revenueGrowth",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="revenuePerShare",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="sandPfiftyTwoWeekChange",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="sharesOutstanding",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="sharesPercentSharesOut",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="sharesShort",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="sharesShortPreviousMonthDate",
            field=models.DateField(default="1901-01-01"),
        ),
        migrations.AddField(
            model_name="stocks",
            name="sharesShortPriorMonth",
            field=models.DateField(default="1901-01-01"),
        ),
        migrations.AddField(
            model_name="stocks",
            name="shortPercentOfFloat",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="shortRatio",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="targetHighPrice",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="targetLowPrice",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="targetMeanPrice",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="targetMedianPrice",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="totalCash",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="totalCashPerShare",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="totalDebt",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="totalRevenue",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="trailingAnnualDividendRate",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="trailingAnnualDividendYield",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="trailingEps",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="trailingPE",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="twoHundredDayAverage",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="volume",
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="forex",
            name="currency_base",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
