# Generated by Django 4.1 on 2023-07-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_stocks_ask_stocks_asksize_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forex",
            name="currency_base",
            field=models.CharField(max_length=30),
        ),
    ]
