# Generated by Django 4.1 on 2023-07-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_forex_currency_base"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crypto",
            name="available_exchanges",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="crypto",
            name="currency_base",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="crypto",
            name="currency_quote",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="forex",
            name="currency_base",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="forex",
            name="currency_group",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="forex",
            name="currency_quote",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="stocks",
            name="company_name",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="stocks",
            name="country",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="stocks",
            name="exchange",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="stocks",
            name="mic_code",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="stocks",
            name="security_type",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
