# Generated by Django 4.1 on 2023-07-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_crypto_available_exchanges_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crypto",
            name="last_updated",
            field=models.DateField(default="1901-01-01"),
        ),
        migrations.AddField(
            model_name="forex",
            name="last_updated",
            field=models.DateField(default="1901-01-01"),
        ),
    ]
